#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

// Prefer SHOPIFY_APP_URL set by Shopify CLI; fallback to SHOPIFY_APP_URL_ORIGIN
const origin = process.env.APP_URL || process.env.SHOPIFY_APP_URL || process.env.SHOPIFY_APP_URL_ORIGIN;

if (!origin) {
  console.error('[gen-env] SHOPIFY_APP_URL not set. Start with `shopify app dev` or set env manually.');
  process.exit(1);
}

const outDir = path.join(__dirname, '..', 'extensions', 'checkout-address-autocomplete', 'src');
const outFile = path.join(outDir, 'app-origin.js');

const content = `// Generated by scripts/gen-env.cjs\nexport const APP_ORIGIN = ${JSON.stringify(origin)};\n`;

try {
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(outFile, content);
  console.log('[gen-env] Wrote APP_ORIGIN to', outFile, '=>', origin);
  process.exit(0);
} catch (err) {
  console.error('[gen-env] Failed to write app origin:', err);
  process.exit(1);
}


